//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package zang.liguang.tube.activity;

import android.content.Context;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.support.v4.view.ViewPager;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import zang.liguang.tube.R.id;
import zang.liguang.tube.R.layout;
import zang.liguang.tube.view.dragpanel.DraggablePanel;
import zang.liguang.tube.wedget.ColumnHorizontalScrollView;

public final class NewYorkTimeActivity_
    extends NewYorkTimeActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_new_york_time);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static NewYorkTimeActivity_.IntentBuilder_ intent(Context context) {
        return new NewYorkTimeActivity_.IntentBuilder_(context);
    }

    public static NewYorkTimeActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new NewYorkTimeActivity_.IntentBuilder_(fragment);
    }

    public static NewYorkTimeActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new NewYorkTimeActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        shade_right = ((ImageView) hasViews.findViewById(id.shade_right));
        mColumnHorizontalScrollView = ((ColumnHorizontalScrollView) hasViews.findViewById(id.mColumnHorizontalScrollView));
        rl_column = ((RelativeLayout) hasViews.findViewById(id.rl_column));
        ll_more_columns = ((LinearLayout) hasViews.findViewById(id.ll_more_columns));
        top_more = ((ImageView) hasViews.findViewById(id.top_more));
        progressBar = ((ProgressBar) hasViews.findViewById(id.progressBar));
        top_head = ((ImageView) hasViews.findViewById(id.top_head));
        button_more_columns = ((ImageView) hasViews.findViewById(id.button_more_columns));
        mViewPager = ((ViewPager) hasViews.findViewById(id.mViewPager));
        draggablePanel = ((DraggablePanel) hasViews.findViewById(id.draggable_panel));
        mRadioGroup_content = ((LinearLayout) hasViews.findViewById(id.mRadioGroup_content));
        shade_left = ((ImageView) hasViews.findViewById(id.shade_left));
        if (button_more_columns!= null) {
            button_more_columns.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NewYorkTimeActivity_.this.onMoreColumns(view);
                }

            }
            );
        }
        if (top_head!= null) {
            top_head.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    NewYorkTimeActivity_.this.onMenu(view);
                }

            }
            );
        }
        initView();
    }

    @Override
    public void setChangelView() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                NewYorkTimeActivity_.super.setChangelView();
            }

        }
        );
    }

    @Override
    public void getYouTubeCatgoryListFromWeb() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    NewYorkTimeActivity_.super.getYouTubeCatgoryListFromWeb();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<NewYorkTimeActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, NewYorkTimeActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), NewYorkTimeActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), NewYorkTimeActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
