//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package zang.liguang.tube.view;

import android.content.Context;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import zang.liguang.tube.R.id;
import zang.liguang.tube.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class RelativeVideoItemView_
    extends RelativeVideoItemView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public RelativeVideoItemView_(Context context) {
        super(context);
        init_();
    }

    public static RelativeVideoItemView build(Context context) {
        RelativeVideoItemView_ instance = new RelativeVideoItemView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.item_new, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        imageLayout = ((LinearLayout) hasViews.findViewById(id.layout_image));
        item_image2 = ((ImageView) hasViews.findViewById(id.item_image_2));
        leftImage = ((ImageView) hasViews.findViewById(id.left_image));
        item_image1 = ((ImageView) hasViews.findViewById(id.item_image_1));
        itemConten = ((TextView) hasViews.findViewById(id.item_content));
        item_image0 = ((ImageView) hasViews.findViewById(id.item_image_0));
        itemTitle = ((TextView) hasViews.findViewById(id.item_title));
        articleLayout = ((RelativeLayout) hasViews.findViewById(id.article_top_layout));
        itemAbstract = ((TextView) hasViews.findViewById(id.item_abstract));
    }

}
